version: 0.1.0.{build}
image: Visual Studio 2017
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
environment:
  appveyor: true
services: mssql2017
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
